name: chat_assignment
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_web_plugins:
    sdk: flutter
  get_it: ^7.7.0
  go_router: ^14.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.4.2
  intl: ^0.19.0
  uuid: ^4.4.0
  web_socket_channel: ^2.4.5

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/
